config/routes.rb
Rails.application.routes.draw do
  root "dashboard#index"
  devise_for :users

  resources :users, path: "/users", only: [] do
    resources :shelters, only: [:edit, :update], path: "/shelters" do
      resources :pets, path: "/pets"
    end

    resources :rescuers, only: [:edit, :update], path: "/rescuers" do
      resources :pets, path: "/pets"
    end

    resources :adopters, only: [:edit, :update], path: "/adopter" do
    end
  end

  resources :pets, only: [:show], path: "/pets"

  scope "/registrations" do
    resources :registrations, only: [:index], path: "/"
    resources :adopters, only: [:new, :create], path: "/adopter"
    resources :rescuers, only: [:new, :create], path: "/rescuer"
    resources :shelters, only: [:new, :create], path: "/shelter"
  end
end

app/models/rescuer.rb
class Rescuer < ApplicationRecord
  has_many :users, as: :userable
  has_many :pets, through: :users

  accepts_nested_attributes_for :users

  validates :name, presence: true, length: {maximum: 80}
end

app/controllers/rescuers_controller.rb
class RescuersController < ApplicationController
  before_action :set_rescuer, only: %i[edit update]

  def new
    @rescuer = Rescuer.new
    @rescuer.users.build
  end

  def create
    @rescuer = Rescuer.new secure_rescuer_params

    lonlat = secure_rescuer_params.dig(:users_attributes, "0", :lonlat).split(",").map(&:to_f)
    if lonlat.size.eql?(2) && lonlat.first&.between?(-180, 180) && lonlat.last&.between?(-90, 90)
      @rescuer.users.first.lonlat = RGeo::Geographic.spherical_factory(srid: 4326).point(*lonlat)
    end

    if @rescuer.save
      redirect_to new_user_session_path, notice: t(".success")
    else
      @rescuer.users.first.address = ""
      @rescuer.users.first.lonlat = nil
      @rescuer.valid?

      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    params_lonlat = secure_rescuer_params.dig(:users_attributes, "0", :lonlat)

    unless @rescuer.users.first.lonlat.to_s.eql? params_lonlat
      new_lonlat = params_lonlat.split(",").map(&:to_f)
      if new_lonlat.size.eql?(2) && new_lonlat.first&.between?(-180, 180) && new_lonlat.last&.between?(-90, 90)

        secure_rescuer_params.tap do |params|
          params[:users_attributes]["0"].delete("lonlat")
          @rescuer.users.first.update!(*params[:users_attributes]["0"])
          params.delete(:users_attributes)
          @rescuer.update!(*params)
        end

        @rescuer.users.first.update!(lonlat: RGeo::Geographic.spherical_factory(srid: 4326).point(*new_lonlat))

        return redirect_to edit_user_rescuer_path, notice: t("notifications.notice.updated")
      end
    end

    secure_rescuer_params.tap do |params|
      params[:users_attributes]["0"].delete("lonlat")
      @rescuer.users.first.update!(*params[:users_attributes]["0"])
      params.delete(:users_attributes)
      @rescuer.update!(*params)
    end

    redirect_to edit_user_rescuer_path, notice: t("notifications.notice.updated")
  rescue
    redirect_to edit_user_rescuer_path, alert: t("notifications.alert.updated")
  end

  private

  def set_rescuer
    @rescuer = Rescuer.find(params[:id])
  end

  def secure_rescuer_params
    params.require(:rescuer).permit(:name, users_attributes: [:email, :password, :password_confirmation, :address, :lonlat, :phone])
  end
end

app/helpers/rescuers_helper.rb
module RescuersHelper
end

app/views/rescuers/edit.html.erb
<h1 class="text-3xl font-semibold text-center text-gray-800 pb-4"><%= t(".header")  %></h1>
<%= form_with scope: @rescuer, url: user_rescuer_path, method: :put, data: { controller: "places", action: "google-maps-callback@window->places#initializeMap" } do |form| %>
  <div class="shadow overflow-hidden sm:rounded-md">
    <div class="px-4 py-5 bg-white sm:p-6">
      <div class="grid grid-cols-6 gap-6">
        <div class="col-span-6 sm:col-span-6 lg:col-span-3">
          <%= form.label :name, class:"block text-sm font-medium text-gray-700" %>
          <%= form.text_field :name, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border border-gray-300 rounded-md" %>
        </div>

        <%= form.fields_for :users do |u| %>
          <div class="col-span-6 sm:col-span-6 lg:col-span-3">
            <%= u.label :email, class:"block text-sm font-medium text-gray-700" %>
            <%= u.text_field :email, class: "mt-1 bg-gray-300 block w-full shadow-sm sm:text-sm border border-gray-300 rounded-md", disabled: true %>
          </div>

          <div class="col-span-6 sm:col-span-6 lg:col-span-3">
            <%= u.label :phone, class:"block text-sm font-medium text-gray-700" %>
            <%= u.telephone_field :phone, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border border-gray-300 rounded-md" %>
          </div>

          <div class="col-span-6 sm:col-span-6 lg:col-span-6 h-2"></div>

          <div class="col-span-6 sm:col-span-6 lg:col-span-6">
            <%= u.label :address, class:"block text-sm font-medium text-gray-700" %>
            <%= u.text_field :address, data: { "places-target": "field", action: "keydown->places#preventSubmit" }, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border border-gray-300 rounded-md" %>
          </div>

          <div class="col-span-6 sm:col-span-6 lg:col-span-6">
            <div data-places-target="map" style="height:400px"></div>
          </div>
          <%= u.text_field :lonlat, data: { "places-target": "latLng" }, class: "hidden" %>
        <% end %>
    </div>
    <div class="bg-gray-50 px-4 py-3 sm:px-6 sm:flex sm:flex-row-reverse">
      <%= form.submit t("form.save"), class: "mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-indigo-600 text-base font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm" %>
      <%= link_to t("form.cancel"), root_path, class:"mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm" %>
    </div>
  </div>
<% end %>

app/views/rescuers/new.html.erb
<div class="mt-5 md:mt-0 md:col-span-2">
 <h1 class="text-3xl font-semibold text-center text-gray-800 pb-4"><%= t(".header")  %></h1>
  <%= form_with scope: @rescuer, url: rescuers_path, data: { controller: "places", action: "google-maps-callback@window->places#initializeMap" } do |form| %>
    <div class="shadow overflow-hidden sm:rounded-md">
      <div class="px-4 py-5 bg-white sm:p-6">
        <div class="grid grid-cols-6 gap-6">
          <div class="col-span-6 sm:col-span-6 lg:col-span-3">
            <%= form.label :name, class:"block text-sm font-medium text-gray-700" %>
            <%= form.text_field :name, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border border-gray-300 rounded-md" %>
            <% if @rescuer.errors[:name].any? %>
              <div class="block text-sm font-medium text-red-700"><%= @rescuer.errors.messages_for(:name).first %></div>
            <% end %>
          </div>

          <%= form.fields_for :users do |u| %>
            <div class="col-span-6 sm:col-span-6 lg:col-span-3">
              <%= u.label :email, class:"block text-sm font-medium text-gray-700" %>
              <%= u.text_field :email, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border border-gray-300 rounded-md" %>
              <% if @rescuer.errors["users.email"].any? %>
                <div class="block text-sm font-medium text-red-700"><%= @rescuer.errors.messages_for("users.email").first %></div>
              <% end %>
            </div>
            <div class="col-span-6 sm:col-span-6 lg:col-span-3">
              <%= u.label :password, class:"block text-sm font-medium text-gray-700" %>
              <%= u.password_field :password, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border border-gray-300 rounded-md" %>
              <% if @rescuer.errors["users.password"].any? %>
                <div class="block text-sm font-medium text-red-700"><%= @rescuer.errors.messages_for("users.password").first %></div>
              <% end %>
            </div>
            <div class="col-span-6 sm:col-span-6 lg:col-span-3">
              <%= u.label :password_confirmation, class:"block text-sm font-medium text-gray-700" %>
              <%= u.password_field :password_confirmation, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border border-gray-300 rounded-md" %>
              <% if @rescuer.errors["users.password_confirmation"].any? %>
                <div class="block text-sm font-medium text-red-700"><%= @rescuer.errors.messages_for("users.password_confirmation").first %></div>
              <% end %>
            </div>

            <div class="col-span-6 sm:col-span-6 lg:col-span-3">
              <%= u.label :phone, class:"block text-sm font-medium text-gray-700" %>
              <%= u.telephone_field :phone, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border border-gray-300 rounded-md" %>
              <% if @rescuer.errors["users.phone"].any? %>
                <div class="block text-sm font-medium text-red-700"><%= @rescuer.errors.messages_for("users.phone").first %></div>
              <% end %>
            </div>

            <div class="col-span-6 sm:col-span-6 lg:col-span-6 h-2"></div>

            <div class="col-span-6 sm:col-span-6 lg:col-span-6">
              <%= u.label :address, class:"block text-sm font-medium text-gray-700" %>
              <%= u.text_field :address, data: { "places-target": "field", action: "keydown->places#preventSubmit" }, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border border-gray-300 rounded-md" %>
              <% if @rescuer.errors["users.lonlat"].any? %>
                <div class="block text-sm font-medium text-red-700"><%= @rescuer.errors.messages_for("users.lonlat").first %></div>
              <% end %>
            </div>

            <div class="col-span-6 sm:col-span-6 lg:col-span-6">
              <div data-places-target="map" style="height:400px"></div>
            </div>
            <%= u.text_field :lonlat, data: { "places-target": "latLng" }, class: "hidden" %>
          <% end %>

        </div>
      </div>
      <div class="bg-gray-50 px-4 py-3 sm:px-6 sm:flex sm:flex-row-reverse">
        <%= form.submit t("form.save"), class: "mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-indigo-600 text-base font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm" %>
        <%= link_to t("form.cancel"), registrations_path, class:"mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm" %>
      </div>
    </div>
  <% end %>
</div>